import "bootstrap/dist/css/bootstrap.css"
import SessionProviderClient from "./sessionProviderClient";

export const metadata = {
  title: {
    default: "ادمین بیمارستان",
    template: "ادمین بیمارستان | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderClient>
        <body style={{ backgroundColor: "rgb(138 ,138 ,138)" }}>{children}</body>
      </SessionProviderClient>
    </html>
  );
}
